# Generated by Django 2.1.4 on 2018-12-22 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examtasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('provided_answer', models.CharField(max_length=1000)),
                ('examowner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owning_user', to=settings.AUTH_USER_MODEL)),
                ('examtask', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task_name', to='examtasks.Examtask')),
                ('examtask_int', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task_integer', to='examtasks.Examtask')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='asnwering_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
