# Generated by Django 2.1.4 on 2018-12-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='examtask_int',
        ),
    ]
