# Generated by Django 2.1.4 on 2018-12-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20181223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='examowner_id',
            field=models.IntegerField(editable=False),
        ),
    ]
