# Generated by Django 2.1.4 on 2018-12-22 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtask_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('taskname', models.CharField(max_length=100)),
                ('taskdescription', models.CharField(max_length=1000)),
                ('points', models.IntegerField(default=1)),
                ('rightanswer', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtasks', to='exams.Exam')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
