# Generated by Django 2.1.4 on 2018-12-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtask',
            name='examtask_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
