# Generated by Django 2.1.4 on 2018-12-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examtasks', '0002_examtask_examtask_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtask',
            old_name='exam',
            new_name='examinstance',
        ),
    ]
